### ISSUE TITLE
[Feature Request] Add Delay for  Hls Playlists

### ISSUE THREAD

**Issue by UrloMythus** [mhdzumair/mediaflow-proxy#11]
Hello, feature request here. 
I was thinking it would be really cool if you could add delay for HLS playlists, since sometimes this is needed to get a flawless playblack. Technically you should be able to obtain this by adding player-buffer="delaynumber" into the EXTINF  

You could add this as a query parameter in HLS endpoint.

**Comment by mhdzumair** [comment]
i don't see the `player-buffer` specification defined under the m3u8 standards https://www.rfc-editor.org/rfc/rfc8216#section-4.3.2.1

**Comment by UrloMythus** [comment]
Ah alright, thought it was there. I will reopen this if I find more infos
