### ISSUE TITLE
Debrid file access limitation

### ISSUE THREAD

**Issue by alvynfash** [mhdzumair/mediaflow-proxy#27]
Will this work with debrid downloads as well ie is it possible to bypass IP address limitations when simultaneously accessing cached debrid content from multiple locations ?

**Comment by mhdzumair** [comment]
Yes, When using MediaFlow with MediaFusion or Jackettio stremio addon then it will use the MediaFlow public ip address instead of client ip. so RD/AD will know about one ip address.
