### ISSUE TITLE
How to apply config in docker

### ISSUE THREAD

**Issue by niravjdn** [mhdzumair/mediaflow-proxy#32]
If I am running mediaflow proxy in docker, how do I apply below config.

I am running it for AD but it doesn't worm from stremio and shows playback error even thought I can reach /docs and other endpoints.

Would applying below config help? If yes, How do I apply it?

`PROXY_URL=http://proxy:8080
ALL_PROXY=true`

**Comment by niravjdn** [comment]
There are the logs I get in my container.

192.168.160.1:58808 - "HEAD /proxy/stream?api_password=squirrel&d=https%3A%2F%2Fo7XXXXXq9.debrid.it%2Fdl%2F3erkxef549f%2FConclave.2024.1080p.WEBRip.x265.10bit.AAC5.1-%255BYTS.MX%255D.mp4&r_Content-Disposition=attachment%3B+filename%3DConclave.2024.1080p.WEBRip.x265.10bit.AAC5.1-%255BYTS.MX%255D.mp4 HTTP/1.1" 403
192.168.160.1:58808 - "GET /proxy/stream?api_password=squirrel&d=https%3A%2F%2Fo7XXXXq9.debrid.it%2Fdl%2F3erkxef549f%2FConclave.2024.1080p.WEBRip.x265.10bit.AAC5.1-%255BYTS.MX%255D.mp4&r_Content-Disposition=attachment%3B+filename%3DConclave.2024.1080p.WEBRip.x265.10bit.AAC5.1-%255BYTS.MX%255D.mp4 HTTP/1.1" 403
192.168.160.1:58808 - "GET /proxy/ip?api_password=squirrel HTTP/1.1" 403

**Comment by mhdzumair** [comment]
To run with docker, for example, if you're running socks5 proxy,

```
docker run --restart unless-stopped -p 8889:8888 -d -e api_password=dedsec -e PROXY_URL="socks5://127.0.0.1:1080" -e ALL_PROXY=true --name mediaflow_proxy mhdzumair/mediaflow-proxy
```

**Comment by mhdzumair** [comment]
Here's how to set it up in Portainer:

1. Click on "Containers" → "Add Container"

2. Basic Configuration:
- Name: `mediaflow_proxy`
- Image: `mhdzumair/mediaflow-proxy`
- Always restart unless stopped: ✓ (Check this option)

3. Port Mapping:
- Host Port: `8889`
- Container Port: `8888`
- Protocol: `TCP`

4. Environment Variables (Add these):
- `api_password` = `password`
- `PROXY_URL` = `socks5://127.0.0.1:1080`
- `ALL_PROXY` = `true`

5. Network Mode:
- Leave as default (bridge)

6. Auto-start container: ✓ (Check this option)

Once you've entered all these settings, click "Deploy the container" to start it. This will create the same container configuration as the Docker command line version.

**Comment by niravjdn** [comment]
Thanks, Really appreciate giving your time to answer.

When I run and try to do speedtest with AD, it fails.

It asks for Password where I enter the password configured in docker environment variable. Then I click on All debrid speedtest and enter API key. but it fails and show this error.


![image](https://github.com/user-attachments/assets/ae8c4eae-4738-4b41-8278-5ffd52d3c285)

**Comment by niravjdn** [comment]
I made sure I enter correct password, and error is this now.

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaflow_proxy/mediaflow_proxy/configs.py", line 44, in get_mounts
    mounts["all://"] = transport_cls(proxy=self.proxy_url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaflow_proxy/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 296, in __init__
    proxy = Proxy(url=proxy) if isinstance(proxy, (str, URL)) else proxy
            ^^^^^^^^^^^^^^^^
  File "/mediaflow_proxy/.venv/lib/python3.12/site-packages/httpx/_config.py", line 214, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('%22socks5://127.0.0.1:1080%22')

**Comment by niravjdn** [comment]
Thanks, Actually it worked with below config.

```
test
```


![image](https://github.com/user-attachments/assets/7bbea6da-a125-46c5-abe9-46c5aadb7c17)

**Comment by mhdzumair** [comment]
Nice, hope your issue is resolved.
