### ISSUE TITLE
Client's IP address when the server is running on a remote server.

### ISSUE THREAD

**Issue by asaddon** [mhdzumair/mediaflow-proxy#6]
Hello, any chance you can add an option to passthrough client's IP address to Debrid Services specially AllDebrid when the server is running on a VPS like you're doing for MediaFusion, as you already know AllDebrid doesnt allow VPS IPs :(

**Comment by mhdzumair** [comment]
You can run warp docker or gluetun docker, then use that socks5 proxy setup into mediaflow. Now you can only proxy the certain url like proxy only AD then follow setting below env in .env

```
proxy_routes='{
    "https://*.alldebrid.com": {
        "proxy_url": "socks5://127.0.0.1:1080"
    },
    "https://*.debrid.it": {
        "proxy_url": "socks5://127.0.0.1:1080"
    }
}'
```

or if you want to enable full proxying then set
```
proxy_default_url="http://127.0.0.1:1081"
```

its support setting http/https/socks proxy
